image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y upgrade
    - apt -y install automake autoconf make
    - apt -y install puredata-dev puredata-core
    - autoreconf -fiv
  script:
    # build multi-object-binary
    - ./configure
    - make check VERBOSE=1
    - make install DESTDIR=${CI_PROJECT_DIR}/ pkglibdir=zexy
#  artifacts:
#    name: ${CI_PROJECT_NAME}-snapshot
#    paths:
#      - zexy
#    expire_in: 1 week

build-obj:
  stage: build
  before_script:
    - apt update && apt -y upgrade
    - apt -y install automake autoconf make
    - apt -y install puredata-dev puredata-core
    - autoreconf -fiv
  script:
    # build multi-object-binary
    - ./configure --disable-library
    - make check VERBOSE=1
    - make install DESTDIR=${CI_PROJECT_DIR}/ pkglibdir=zexy

build-distcheck:
  stage: build
  before_script:
    - apt update && apt -y upgrade
    - apt -y install automake autoconf make
    - apt -y install puredata-dev puredata-core
    - autoreconf -fiv
  script:
    # finally make distcheck
    - ./configure
    - make distcheck
